# ============================================================
# zweitstimme_pipeline.R
# Data pipeline for the Bundestagswahl 2025 forecast explainer
# GRAD-E1493 · Hertie School · May 2026
#
# FOLDER STRUCTURE:
#   zweitstimme-explainer/
#   ├── index.html
#   ├── zweitstimme_pipeline.R
#   ├── data/
#   │   ├── input/
#   │   │   ├── forecast.json                  <- UPLOAD MANUALLY
#   │   │   ├── polls.json                     <- UPLOAD MANUALLY
#   │   │   ├── BTW_21_kerg2.csv               <- UPLOAD MANUALLY
#   │   │   ├── BTW_25_kerg2.csv               <- UPLOAD MANUALLY
#   │   │   └── prediction_data_districts.rds  <- downloaded by script
#   │   └── output/                            <- generated by script
#   └── README.md
#
# MANUAL UPLOADS (place in data/input/ before running):
#   forecast.json    <- originally 1778865796898_forecast.json
#   polls.json       <- originally 1778865796899_polls.json
#   BTW_21_kerg2.csv <- originally 1778932219123_BTW_21_Result_per_WK.csv
#   BTW_25_kerg2.csv <- originally 1778932573175_kerg2.csv
#
# DEPENDENCIES:
#   install.packages(c("tidyverse", "httr", "jsonlite"))
# ============================================================

library(tidyverse)
library(httr)
library(jsonlite)

dir.create("data/input",  showWarnings = FALSE, recursive = TRUE)
dir.create("data/output", showWarnings = FALSE, recursive = TRUE)

PARTIES       <- c("CDU/CSU", "SPD", "AfD", "Grune", "FDP", "Linke", "BSW")
ELECTION_DATE <- as.Date("2025-02-23")

normalise_party <- function(x) {
  case_when(
    x %in% c("CDU", "CSU", "CDU_CSU", "CDU/CSU") ~ "CDU/CSU",
    x %in% c("GRUNE", "GRUENE", "Grune", "Grüne") ~ "Grune",
    x %in% c("Die Linke", "LINKE", "Linke")        ~ "Linke",
    x %in% c("AFD", "AfD")                          ~ "AfD",
    TRUE                                             ~ x
  )
}

fetch_all_pages <- function(base_url) {
  results <- list()
  page <- 1
  repeat {
    resp <- GET(paste0(base_url, "?page=", page, "&limit=1000"))
    if (status_code(resp) != 200) stop("API error ", status_code(resp))
    raw   <- content(resp, as = "text", encoding = "UTF-8") |> fromJSON()
    items <- raw$items
    if (is.null(items) || nrow(items) == 0) break
    results[[page]] <- items
    fetched <- sum(map_int(results, nrow))
    total   <- raw$meta$total
    if (is.null(total) || fetched >= total) break
    page <- page + 1
  }
  bind_rows(results)
}

# ============================================================
# 1. POLL DATA — live from Zweitstimme API
# ============================================================
cat("1. Fetching poll data from API...\n")

polls_raw <- fetch_all_pages("https://api.fasttrack29.com/v1/results")

polls <- polls_raw |>
  mutate(
    date  = as.Date(publish_date),
    party = normalise_party(party_short_name)
  ) |>
  filter(
    date  >= as.Date("2024-10-01"),
    date  <= ELECTION_DATE,
    scope == "federal",
    party %in% PARTIES
  ) |>
  select(poll_id, date, institute = institute_name, party, share = percentage)

write_csv(polls, "data/output/polls_campaign.csv")
cat("   Saved:", n_distinct(polls$poll_id), "polls\n")

# ============================================================
# 2. FORECAST TIME SERIES — from archived JSON snapshot
# ============================================================
cat("2. Loading forecast time series from archived snapshot...\n")

forecast_path <- "data/input/forecast.json"
if (!file.exists(forecast_path)) {
  stop("Missing: ", forecast_path, "\nPlace forecast.json in data/input/")
}

forecast_raw <- fromJSON(forecast_path, flatten = TRUE)
forecast <- if (is.data.frame(forecast_raw)) as_tibble(forecast_raw) else as_tibble(forecast_raw$items %||% forecast_raw[[1]])
if ("date" %in% names(forecast)) forecast <- mutate(forecast, date = as.Date(date))

write_csv(forecast, "data/output/forecast_trend.csv")
cat("   Saved:", nrow(forecast), "rows, columns:", paste(names(forecast), collapse = ", "), "\n")

# ============================================================
# 3. 2021 CONSTITUENCY RESULTS — from local file
#    Wide format: CDU_Stimme1, SPD_Stimme1, etc.
# ============================================================
cat("3. Loading 2021 constituency results...\n")

btw21_path <- "data/input/BTW_21_kerg2.csv"
if (!file.exists(btw21_path)) stop("Missing: ", btw21_path)

btw21_raw <- read_csv(btw21_path, show_col_types = FALSE)

btw21_wk <- btw21_raw |>
  mutate(wkr = as.integer(Gebietsnummer), wkr_name = Gebietsname) |>
  select(wkr, wkr_name,
         CDU   = matches("^CDU_Stimme1$"),
         CSU   = matches("^CSU_Stimme1$"),
         SPD   = matches("^SPD_Stimme1$"),
         Grune = matches("^GR.NE_Stimme1$"),
         AfD   = matches("^AfD_Stimme1$"),
         Linke = matches("^DIE LINKE_Stimme1$"),
         FDP   = matches("^FDP_Stimme1$")) |>
  mutate(across(CDU:FDP, as.numeric),
         CDU_CSU = rowSums(cbind(CDU, CSU), na.rm = TRUE)) |>
  select(-CDU, -CSU) |>
  pivot_longer(c(SPD, Grune, AfD, Linke, FDP, CDU_CSU),
               names_to = "party_raw", values_to = "vote_share_2021") |>
  mutate(party = case_when(
    party_raw == "CDU_CSU" ~ "CDU/CSU",
    party_raw == "Grune"   ~ "Grune",
    TRUE                   ~ party_raw
  )) |>
  filter(!is.na(vote_share_2021))

write_csv(btw21_wk, "data/output/btw21_constituency_first_vote.csv")
cat("   Saved:", nrow(btw21_wk), "rows\n")

# ============================================================
# 4. 2025 CONSTITUENCY RESULTS — from local file
#    Long format (kerg2): Gebietsart, Stimme, Gruppenart, Prozent
# ============================================================
cat("4. Loading 2025 constituency results...\n")

btw25_path <- "data/input/BTW_25_kerg2.csv"
if (!file.exists(btw25_path)) stop("Missing: ", btw25_path)

btw25_winners <- read_delim(btw25_path, delim = ";", skip = 9,
                            locale = locale(decimal_mark = ","),
                            show_col_types = FALSE) |>
  filter(Gebietsart == "Wahlkreis", Stimme == 1,
         Gruppenart == "Partei", !is.na(Prozent)) |>
  transmute(
    wkr        = as.integer(Gebietsnummer),
    party      = normalise_party(Gruppenname),
    vote_share = as.numeric(Prozent)
  ) |>
  group_by(wkr, party) |>
  summarise(vote_share = sum(vote_share, na.rm = TRUE), .groups = "drop") |>
  group_by(wkr) |>
  slice_max(vote_share, n = 1) |>
  ungroup() |>
  rename(actual_winner = party, actual_share = vote_share)

write_csv(btw25_winners, "data/output/btw25_constituency_winners.csv")
cat("   Saved:", nrow(btw25_winners), "rows\n")

# ============================================================
# 5. CONSTITUENCY MODEL PREDICTIONS — replication repo
# ============================================================
cat("5. Fetching constituency model predictions...\n")

pred_rds <- "data/input/prediction_data_districts.rds"
tryCatch({
  download.file(
    "https://github.com/zweitstimme-org/prediction-2025-replication/raw/main/output/prediction_data_districts.rds",
    pred_rds, mode = "wb", quiet = TRUE
  )
  pred_data <- readRDS(pred_rds)
  write_csv(pred_data, "data/output/prediction_data_districts.csv")
  cat("   Saved:", nrow(pred_data), "rows\n")
}, error = function(e) {
  cat("   WARNING: Could not download. Get manually from:\n")
  cat("   https://github.com/zweitstimme-org/prediction-2025-replication\n")
  cat("   Save to: data/input/prediction_data_districts.rds\n")
})

# ============================================================
# 6. HOUSE EFFECTS
# ============================================================
cat("6. Computing house effects...\n")

house_effects <- polls |>
  group_by(institute, party) |>
  summarise(inst_avg = mean(share, na.rm = TRUE), .groups = "drop") |>
  group_by(party) |>
  mutate(field_avg    = mean(inst_avg, na.rm = TRUE),
         house_effect = round(inst_avg - field_avg, 2)) |>
  ungroup() |>
  arrange(party, desc(house_effect))

write_csv(house_effects, "data/output/house_effects.csv")
cat("   Saved:", nrow(house_effects), "rows\n")

# ============================================================
# 7. TIME WINDOW POLL ESTIMATES
# ============================================================
cat("7. Computing time window estimates...\n")

windows <- tibble(
  label     = c("4 months prior", "3 months prior", "1 month prior", "Final (2 days)"),
  date_from = ELECTION_DATE - c(150, 100, 40, 5),
  date_to   = ELECTION_DATE - c(90,  60,  10, 1)
)

window_estimates <- windows |>
  rowwise() |>
  reframe({
    polls |>
      filter(date >= date_from, date <= date_to) |>
      group_by(institute, party) |>
      summarise(inst_avg = mean(share, na.rm = TRUE), .groups = "drop") |>
      group_by(party) |>
      summarise(estimate = round(mean(inst_avg, na.rm = TRUE), 1), .groups = "drop") |>
      mutate(window = label)
  })

write_csv(window_estimates, "data/output/time_window_estimates.csv")
cat("   Saved:", nrow(window_estimates), "rows\n")

# ============================================================
# SUMMARY
# ============================================================
cat("\n============================================================\n")
cat("Pipeline complete.\n\n")
cat("Input files used (data/input/):\n")
cat("  forecast.json                    <- archived API snapshot\n")
cat("  polls.json                       <- archived API snapshot\n")
cat("  BTW_21_kerg2.csv                 <- uploaded manually\n")
cat("  BTW_25_kerg2.csv                 <- uploaded manually\n")
cat("  prediction_data_districts.rds    <- downloaded from replication repo\n")
cat("\nOutput files generated (data/output/):\n")
cat("  polls_campaign.csv\n")
cat("  forecast_trend.csv\n")
cat("  btw21_constituency_first_vote.csv\n")
cat("  btw25_constituency_winners.csv\n")
cat("  prediction_data_districts.csv\n")
cat("  house_effects.csv\n")
cat("  time_window_estimates.csv\n")
cat("============================================================\n\n")
sessionInfo()
